[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
brotli = "8.0.0"
flate2 = "1.1.1"
hostname = "0.4.0"
native-tls = "0.2.14"
regex = "1.11.1"
rustls = "0.23.26"
tokio-rustls = "0.26.2"
url = "2.5.4"
webpki = "0.22.4"
webpki-roots = "0.26.8"
